// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbJfOP-OLLro2f4BodBrjBKquh-GXICRs',
    appId: '1:833803086396:android:8b0d6911b104a3bf7eb139',
    messagingSenderId: '833803086396',
    projectId: 'expenses-tracking-73d36',
    storageBucket: 'expenses-tracking-73d36.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHVBxsOWx_CMqeVA0MVfzmk6xKGIF8UPs',
    appId: '1:833803086396:ios:3cd3e350dcb41c387eb139',
    messagingSenderId: '833803086396',
    projectId: 'expenses-tracking-73d36',
    storageBucket: 'expenses-tracking-73d36.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracking',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjMmFftO6AWbjNV6Qf3hqp-9wTxRRuFag',
    appId: '1:833803086396:web:e684292bd0abdb2a7eb139',
    messagingSenderId: '833803086396',
    projectId: 'expenses-tracking-73d36',
    authDomain: 'expenses-tracking-73d36.firebaseapp.com',
    storageBucket: 'expenses-tracking-73d36.firebasestorage.app',
    measurementId: 'G-1EN8029CZT',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjMmFftO6AWbjNV6Qf3hqp-9wTxRRuFag',
    appId: '1:833803086396:web:d328bf0ae912b6a47eb139',
    messagingSenderId: '833803086396',
    projectId: 'expenses-tracking-73d36',
    authDomain: 'expenses-tracking-73d36.firebaseapp.com',
    storageBucket: 'expenses-tracking-73d36.firebasestorage.app',
    measurementId: 'G-5ZVKHG0Q2R',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHVBxsOWx_CMqeVA0MVfzmk6xKGIF8UPs',
    appId: '1:833803086396:ios:3cd3e350dcb41c387eb139',
    messagingSenderId: '833803086396',
    projectId: 'expenses-tracking-73d36',
    storageBucket: 'expenses-tracking-73d36.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracking',
  );
}
